[network]
network = "Regtest"
listen_addr = "0.0.0.0:8233"

[consensus]
checkpoint_sync = false

[state]
cache_dir = "/var/zebra/state"

[rpc]
listen_addr = "0.0.0.0:8232"
enable_cookie_auth = false

[mining]
internal_miner = true
miner_address = "tmBsTi2xWTjUdEXnuTceL7fecEQKeWaPDJd"

[network.testnet_parameters.activation_heights]
NU5 = 1